
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 51
#define YY_END_OF_BUFFER 52
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[257] =
    {   0,
        0,    0,   52,   50,   49,    1,   50,   42,   43,   47,
       47,    2,   38,   39,   48,   48,   48,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   44,   45,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   40,   41,   46,
       49,    0,   35,    0,    0,   36,    2,   33,   48,   34,
       32,   32,   32,   32,   32,   21,   32,   32,   26,   32,
       23,   32,   28,   32,   32,   32,   32,   32,   16,   32,
       32,   32,   32,   32,   31,   31,   31,   31,   31,   21,
       31,   31,   31,   26,   31,   23,   31,   28,   31,   31,

       31,   31,   31,   16,   31,   31,   31,   31,   31,   31,
        0,    0,   36,   32,   32,   32,   32,   32,   32,   22,
       32,   32,   32,   32,   27,   32,   10,   14,   32,   32,
       32,   32,   32,   31,   31,   31,   31,   31,   31,   31,
       22,   31,   31,   31,   31,   27,   31,   10,   14,   31,
       31,   31,   31,   31,   31,   37,   32,   15,   32,   32,
       25,   17,   32,   32,   32,   32,   32,   19,   32,   20,
       32,   24,   32,   31,   15,   31,   31,   25,   17,   31,
       31,   31,   31,   31,   31,   19,   31,   20,   31,   24,
       29,   31,   11,    5,   32,   32,   32,   32,   32,   32,

       32,   32,   18,   11,    5,   31,   30,   31,   31,   31,
       31,   31,   31,   31,   18,   32,   32,    4,   32,   32,
       13,   32,    9,   31,   31,    4,   31,   31,   13,   31,
        9,   32,   32,   32,   32,    3,   31,   31,   31,   31,
        3,   12,   32,    7,   32,   12,   31,    7,   31,   32,
        6,   31,    6,    8,    8,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    1,    5,
        6,    7,    8,    8,    9,    8,    8,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   11,   12,   13,
       14,   15,    1,    1,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       25,   32,   33,   34,   35,   36,   37,   25,   25,   25,
       38,   39,   40,    1,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   51,   58,   59,   60,   61,   62,   63,   51,
       51,   51,   64,    1,   65,   66,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[67] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[262] =
    {   0,
        0,    0,  463,  479,  455,  479,   63,  449,  479,  479,
      445,  443,  479,  479,   59,  437,  437,    0,   37,   54,
       41,   45,   50,   54,   59,   73,   64,   96,   68,   67,
       68,  479,  479,    0,   60,  104,   69,   94,  106,  111,
      103,  115,  103,  112,  117,  132,  118,  479,  479,  479,
      447,  139,  479,  445,  440,    0,  436,  479,  479,  479,
        0,  131,  136,  156,  144,    0,  141,  159,    0,  144,
        0,  148,  157,  146,  149,  154,  148,  152,    0,  169,
      158,  155,  172,  169,    0,  174,  163,  181,  174,    0,
      171,  191,  189,    0,  189,    0,  193,  202,  190,  193,

      198,  194,  198,    0,  216,  205,  203,  218,  204,  216,
      438,   70,    0,  225,  223,  211,  211,  226,  230,    0,
      229,  229,  235,  238,    0,  242,    0,    0,  250,  250,
      243,  250,  253,  267,  264,  253,  253,  268,  271,  257,
        0,  265,  271,  273,  266,    0,  266,    0,    0,  272,
      273,  266,  278,  288,  284,  437,  294,    0,  292,  304,
        0,    0,  309,  298,  299,  300,  311,    0,  320,    0,
      306,    0,  319,  314,    0,  308,  318,    0,    0,  323,
      324,  313,  315,  316,  325,    0,  334,    0,  320,    0,
        0,  333,    0,    0,  330,  332,  329,  348,  356,  361,

      359,  353,    0,    0,    0,  354,    0,  356,  353,  364,
      369,  372,  370,  364,    0,  359,  375,    0,  362,  381,
        0,  379,    0,  365,  381,    0,  368,  388,    0,  385,
        0,  391,  383,  382,  406,    0,  409,  403,  400,  416,
        0,    0,  401,    0,  416,    0,  405,    0,  420,  409,
        0,  410,    0,    0,    0,  479,  469,   91,   83,  472,
      475
    } ;

static yyconst flex_int16_t yy_def[262] =
    {   0,
      256,    1,  256,  256,  256,  256,  257,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  256,  256,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  256,  256,  256,
      256,  257,  256,  257,  260,  261,  256,  256,  256,  256,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,

      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      260,  260,  261,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  260,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  258,  258,  258,  258,  258,  258,  258,  258,

      258,  258,  258,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  258,  258,  258,  258,  258,
      258,  258,  258,  259,  259,  259,  259,  259,  259,  259,
      259,  258,  258,  258,  258,  258,  259,  259,  259,  259,
      259,  258,  258,  258,  258,  259,  259,  259,  259,  258,
      258,  259,  259,  258,  259,    0,  256,  256,  256,  256,
      256
    } ;

static yyconst flex_int16_t yy_nxt[546] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   18,   18,   24,   18,   18,   25,   18,   26,   27,
       28,   29,   18,   30,   18,   18,   31,   32,    4,   33,
        4,   34,   35,   36,   37,   38,   39,   34,   34,   40,
       34,   34,   41,   34,   42,   43,   44,   45,   34,   46,
       34,   34,   47,   48,   49,   50,   53,   58,   62,   63,
       66,   67,   59,   69,   71,  156,  112,   68,   75,   70,
       64,   72,   73,   65,   79,   85,   74,   82,   76,   83,
       84,   86,   77,   61,   62,   63,   66,   67,   90,   69,

       71,   54,   78,   68,   75,   70,   64,   72,   73,   65,
       79,   80,   74,   82,   76,   83,   84,   86,   77,   87,
       91,   93,  100,  104,   90,   81,   92,  105,   78,   94,
       88,   96,  101,   89,  102,   95,  107,   80,   97,   98,
      110,  106,   53,   99,  103,   87,   91,   93,  100,  104,
      114,   81,   92,  105,  108,   94,   88,   96,  101,   89,
      102,   95,  107,  109,   97,   98,  110,  106,  115,   99,
      103,  116,  117,  118,  119,  120,  114,   54,  121,  122,
      108,  124,  125,  126,  127,  128,  129,  130,  131,  109,
      123,  132,  133,  134,  115,  135,  136,  116,  117,  118,

      119,  120,  137,  138,  121,  122,  139,  124,  125,  126,
      127,  128,  129,  130,  131,  140,  123,  132,  133,  134,
      141,  135,  136,  142,  143,  145,  146,  147,  137,  138,
      148,  149,  139,  150,  151,  144,  152,  153,  154,  155,
      157,  140,  158,  159,  160,  161,  141,  162,  165,  142,
      143,  145,  146,  147,  166,  163,  148,  149,  164,  150,
      151,  144,  152,  153,  154,  155,  157,  167,  158,  159,
      160,  161,  168,  162,  165,  169,  170,  171,  172,  173,
      166,  163,  174,  175,  164,  176,  177,  178,  179,  180,
      183,  181,  184,  167,  182,  185,  186,  187,  168,  188,

      189,  169,  170,  171,  172,  173,  190,  191,  174,  175,
      192,  176,  177,  178,  179,  180,  183,  181,  184,  193,
      182,  185,  186,  187,  194,  188,  189,  195,  196,  197,
      198,  199,  190,  191,  200,  201,  192,  202,  203,  204,
      205,  206,  207,  208,  209,  193,  210,  211,  212,  213,
      194,  214,  215,  195,  196,  197,  198,  199,  216,  217,
      200,  201,  218,  202,  203,  204,  205,  206,  207,  208,
      209,  219,  210,  211,  212,  213,  220,  214,  215,  221,
      222,  223,  224,  225,  216,  217,  226,  227,  218,  228,
      229,  230,  231,  232,  233,  234,  235,  219,  236,  237,

      238,  239,  220,  240,  241,  221,  222,  223,  224,  225,
      242,  243,  226,  227,  244,  228,  229,  230,  231,  232,
      233,  234,  235,  245,  236,  237,  238,  239,  246,  240,
      241,  247,  248,  249,  250,  251,  242,  243,  252,  253,
      244,  254,  255,  112,  112,   57,  112,  256,   51,  245,
       59,   60,   57,   56,  246,   55,   51,  247,  248,  249,
      250,  251,  256,  256,  252,  253,  256,  254,  255,   52,
       52,   52,  111,  111,  111,  113,  256,  113,    3,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,

      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256
    } ;

static yyconst flex_int16_t yy_chk[546] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    7,   15,   19,   20,
       21,   22,   15,   23,   24,  112,  112,   22,   25,   23,
       20,   24,   24,   20,   27,  259,   24,   29,   25,   30,
       31,   35,   26,  258,   19,   20,   21,   22,   37,   23,

       24,    7,   26,   22,   25,   23,   20,   24,   24,   20,
       27,   28,   24,   29,   25,   30,   31,   35,   26,   36,
       38,   39,   41,   43,   37,   28,   38,   44,   26,   39,
       36,   40,   41,   36,   42,   39,   45,   28,   40,   40,
       47,   44,   52,   40,   42,   36,   38,   39,   41,   43,
       62,   28,   38,   44,   46,   39,   36,   40,   41,   36,
       42,   39,   45,   46,   40,   40,   47,   44,   63,   40,
       42,   64,   65,   67,   68,   70,   62,   52,   72,   73,
       46,   74,   75,   76,   77,   78,   80,   81,   82,   46,
       73,   83,   84,   86,   63,   87,   88,   64,   65,   67,

       68,   70,   89,   91,   72,   73,   92,   74,   75,   76,
       77,   78,   80,   81,   82,   93,   73,   83,   84,   86,
       95,   87,   88,   97,   98,   99,  100,  101,   89,   91,
      102,  103,   92,  105,  106,   98,  107,  108,  109,  110,
      114,   93,  115,  116,  117,  118,   95,  119,  122,   97,
       98,   99,  100,  101,  123,  121,  102,  103,  121,  105,
      106,   98,  107,  108,  109,  110,  114,  124,  115,  116,
      117,  118,  126,  119,  122,  129,  130,  131,  132,  133,
      123,  121,  134,  135,  121,  136,  137,  138,  139,  140,
      143,  142,  144,  124,  142,  145,  147,  150,  126,  151,

      152,  129,  130,  131,  132,  133,  153,  154,  134,  135,
      155,  136,  137,  138,  139,  140,  143,  142,  144,  157,
      142,  145,  147,  150,  159,  151,  152,  160,  163,  164,
      165,  166,  153,  154,  167,  169,  155,  171,  173,  174,
      176,  177,  180,  181,  182,  157,  183,  184,  185,  187,
      159,  189,  192,  160,  163,  164,  165,  166,  195,  196,
      167,  169,  197,  171,  173,  174,  176,  177,  180,  181,
      182,  198,  183,  184,  185,  187,  199,  189,  192,  200,
      201,  202,  206,  208,  195,  196,  209,  210,  197,  211,
      212,  213,  214,  216,  217,  219,  220,  198,  222,  224,

      225,  227,  199,  228,  230,  200,  201,  202,  206,  208,
      232,  233,  209,  210,  234,  211,  212,  213,  214,  216,
      217,  219,  220,  235,  222,  224,  225,  227,  237,  228,
      230,  238,  239,  240,  243,  245,  232,  233,  247,  249,
      234,  250,  252,  156,  111,   57,   55,   54,   51,  235,
       17,   16,   12,   11,  237,    8,    5,  238,  239,  240,
      243,  245,    3,    0,  247,  249,    0,  250,  252,  257,
      257,  257,  260,  260,  260,  261,    0,  261,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,

      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/lex.l"
#line 2 "src/lex.l"
#include <iostream>
#include <math.h>
#include <set>
#include <string>

using namespace std;
int numInteger = 0, numIdentifier = 0, numType = 0;
int numKeyPackage = 0, numKeyImport = 0, numKeyClass = 0, numKeyInterface = 0;
int numKeyInherits = 0, numKeyImplements = 0, numKeyReturn = 0, numKeyNew = 0;
int numKeyBreak = 0, numKeyContinue = 0, numKeyIsvoid = 0, numKeyNot = 0;
int numKeyCase = 0, numKeyOf = 0, numKeyEsac = 0, numKeyWhile = 0;
int numKeyLoop = 0, numKeyPool = 0, numKeyDo = 0, numKeyFor = 0;
int numKeyIf = 0, numKeyThen = 0, numKeyElse = 0, numKeyFi = 0;
int numKeyLet = 0, numKeyIn = 0, numKeyTrue = 0, numKeyFalse = 0;
int numOpArithmetic = 0, numOpRelational = 0;
int numOpAsgn = 0, numOpImplies = 0;
int numColon = 0, numStmtTerminator = 0;
int numBlockBegin = 0, numBlockEnd = 0;
int numParanOpen = 0, numParanClose = 0;
int numArrayOpen = 0, numArrayClose = 0;
int line_ctr=0;
set<string> s_integer, s_identifiers, s_type;
set<string> s_op_arithmetic, s_op_relational;
set<string>	s_strings;
set<string> s_unrecog;
set<string> s_char;
#line 692 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 80 "src/lex.l"

#line 881 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 257 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 479 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 81 "src/lex.l"
{
					line_ctr++;
				}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 84 "src/lex.l"
{
					printf("[INTEGER : %s] (%d)\n", yytext, atoi(yytext));
					++numInteger;
					s_integer.insert(yytext);
				}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 89 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyPackage;
				}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 93 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyImport;
				}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 97 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyClass;
				}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 101 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyInterface;
				}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 105 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyInherits;
				}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 109 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyImplements;
				}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 113 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyReturn;
				}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 117 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyNew;
				}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 121 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyBreak;
				}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 125 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyContinue;
				}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 129 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyIsvoid;
				}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 133 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyNot;
				}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 137 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyCase;
				}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 141 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyOf;
				}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 145 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyEsac;
				}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 149 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyWhile;
				}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 153 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyLoop;
				}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 157 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyPool;
				}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 161 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyDo;
				}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 165 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyFor;
				}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 169 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyIf;
				}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 173 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyThen;
				}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 177 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyElse;
				}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 181 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyFi;
				}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 185 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyLet;
				}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 189 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyIn;
				}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 193 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyTrue;
				}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 197 "src/lex.l"
{
					printf("[KEYWORD: %s]\n", yytext);
					++numKeyFalse;
				}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 201 "src/lex.l"
{
					printf("[IDENTIFIER: %s]\n", yytext);
					++numIdentifier;
					s_identifiers.insert(yytext);
				}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 206 "src/lex.l"
{
					printf("[TYPE: %s]\n", yytext);
					++numType;
					s_type.insert(yytext);
				}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 211 "src/lex.l"
{
					printf("OP_ASGN\n");
					++numOpAsgn;
				}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 215 "src/lex.l"
{
					printf("OP_IMPLIES\n");
					++numOpImplies;
				}
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 219 "src/lex.l"
{
					cout<<"[String:"<<yytext<<" ]"<<endl;
					s_strings.insert(yytext);
				}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 223 "src/lex.l"
{
					cout<<"COMMENTING:"<<yytext<<endl;
				}
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 226 "src/lex.l"
{
					cout<<"M_COMMENTING:"<<yytext<<endl;
				}			
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 229 "src/lex.l"
{
					printf("COLON\n");
					++numColon;
				}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 233 "src/lex.l"
{
					printf("STMT_TERMINATOR\n");
					++numStmtTerminator;
				}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 237 "src/lex.l"
{
					printf("BLOCK_BEGIN\n");
					++numBlockBegin;
				}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 241 "src/lex.l"
{
					printf("BLOCK_END\n");
					++numBlockEnd;
				}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 245 "src/lex.l"
{
					printf("PARAN_OPEN\n");
					++numParanOpen;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 249 "src/lex.l"
{
					printf("PARAN_CLOSE\n");
					++numParanClose;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 253 "src/lex.l"
{
					printf("ARRAY_OPEN\n");
					++numArrayOpen;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 257 "src/lex.l"
{
					printf("ARRAY_CLOSE\n");
					++numArrayClose;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 261 "src/lex.l"
{
					printf("[OP_ARITHMETIC_U: %s]\n", yytext);
					++numOpArithmetic;
					s_op_arithmetic.insert(yytext);
				}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 266 "src/lex.l"
{
					printf("[OP_ARITHMETIC_B: %s]\n", yytext);
					++numOpArithmetic;
					s_op_arithmetic.insert(yytext);
				}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 271 "src/lex.l"
{
					printf("[OP_RELATIONAL: %s]\n", yytext);
					++numOpRelational;
					s_op_relational.insert(yytext);
				}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 276 "src/lex.l"
/* eat up white spaces */
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 277 "src/lex.l"
{
					printf("This one is Unrecognized character: %s--------------------------------------------------------------------------Line %d\n", yytext,line_ctr);
					s_unrecog.insert(yytext);
				}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 281 "src/lex.l"
ECHO;
	YY_BREAK
#line 1372 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 257 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 257 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 256);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 281 "src/lex.l"


void printset(set<string> myset){
	set<string>::iterator iter=myset.begin();
	if(myset.empty())	return;
	cout<<(*iter)<<" ";
	for(iter=myset.begin(); iter!=myset.end();++iter){
		if(iter!=myset.begin())
			cout<<endl<<"								"<<(*iter);
	}
}
int main(int argc, char **argv)
{
	++argv, --argc;
	if (argc > 0)
		yyin = fopen(argv[0], "r");
	else
		yyin = stdin;
	yylex();
	cout<<"TOKENS 					"<<"COUNT	"<<"		VALUE"<<endl;
	cout<<"--------------------------------------------------------------------------"<<endl;
	
	// keywords start
	if (numKeyPackage) {
		cout<<"KEY_PACKAGE:				"<<numKeyPackage<<"			";
		cout<<"package";
		cout<<endl;
	}
	if (numKeyImport) {
		cout<<"KEY_IMPORT:				"<<numKeyImport<<"			";
		cout<<"import";
		cout<<endl;
	}
	if (numKeyClass) {
		cout<<"KEY_CLASS:				"<<numKeyClass<<"			";
		cout<<"class";
		cout<<endl;
	}
	if (numKeyInterface) {
		cout<<"KEY_INTERFACE:				"<<numKeyInterface<<"			";
		cout<<"interface";
		cout<<endl;
	}
	if (numKeyInherits) {
		cout<<"KEY_INHERITS:				"<<numKeyInherits<<"			";
		cout<<"inherits";
		cout<<endl;
	}
	if (numKeyImplements) {
		cout<<"KEY_IMPLEMENTS:				"<<numKeyImplements<<"			";
		cout<<"implements";
		cout<<endl;
	}
	if (numKeyReturn) {
		cout<<"KEY_RETURN:				"<<numKeyReturn<<"			";
		cout<<"return";
		cout<<endl;
	}
	if (numKeyNew) {
		cout<<"KEY_NEW:				"<<numKeyNew<<"			";
		cout<<"new";
		cout<<endl;
	}
	if (numKeyBreak) {
		cout<<"KEY_BREAK:				"<<numKeyBreak<<"			";
		cout<<"break";
		cout<<endl;
	}
	if (numKeyContinue) {
		cout<<"KEY_CONTINUE:				"<<numKeyContinue<<"			";
		cout<<"continue";
		cout<<endl;
	}
	if (numKeyIsvoid) {
		cout<<"KEY_ISVOID:				"<<numKeyIsvoid<<"			";
		cout<<"isvoid";
		cout<<endl;
	}
	if (numKeyNot) {
		cout<<"KEY_NOT:				"<<numKeyNot<<"			";
		cout<<"not";
		cout<<endl;
	}
	if (numKeyCase) {
		cout<<"KEY_CASE:				"<<numKeyCase<<"			";
		cout<<"case";
		cout<<endl;
	}
	if (numKeyOf) {
		cout<<"KEY_OF:					"<<numKeyOf<<"			";
		cout<<"of";
		cout<<endl;
	}
	if (numKeyEsac) {
		cout<<"KEY_ESAC:				"<<numKeyEsac<<"			";
		cout<<"esac";
		cout<<endl;
	}
	if (numKeyWhile) {
		cout<<"KEY_WHILE:				"<<numKeyWhile<<"			";
		cout<<"while";
		cout<<endl;
	}
	if (numKeyLoop) {
		cout<<"KEY_LOOP:				"<<numKeyLoop<<"			";
		cout<<"loop";
		cout<<endl;
	}
	if (numKeyPool) {
		cout<<"KEY_POOL:				"<<numKeyPool<<"			";
		cout<<"pool";
		cout<<endl;
	}
	if (numKeyDo) {
		cout<<"KEY_DO:					"<<numKeyDo<<"			";
		cout<<"do";
		cout<<endl;
	}
	if (numKeyFor) {
		cout<<"KEY_FOR:				"<<numKeyFor<<"			";
		cout<<"for";
		cout<<endl;
	}
	if (numKeyIf) {
		cout<<"KEY_IF:					"<<numKeyIf<<"			";
		cout<<"if";
		cout<<endl;
	}
	if (numKeyThen) {
		cout<<"KEY_THEN:				"<<numKeyThen<<"			";
		cout<<"then";
		cout<<endl;
	}
	if (numKeyElse) {
		cout<<"KEY_ELSE:				"<<numKeyElse<<"			";
		cout<<"else";
		cout<<endl;
	}
	if (numKeyFi) {
		cout<<"KEY_FI:					"<<numKeyFi<<"			";
		cout<<"fi";
		cout<<endl;
	}
	if (numKeyLet) {
		cout<<"KEY_LET:				"<<numKeyLet<<"			";
		cout<<"let";
		cout<<endl;
	}
	if (numKeyIn) {
		cout<<"KEY_IN:					"<<numKeyIn<<"			";
		cout<<"in";
		cout<<endl;
	}
	if (numKeyTrue) {
		cout<<"KEY_TRUE:				"<<numKeyTrue<<"			";
		cout<<"true";
		cout<<endl;
	}
	if (numKeyFalse) {
		cout<<"KEY_FALSE:				"<<numKeyFalse<<"			";
		cout<<"false";
		cout<<endl;
	}
	// keywords end

	if (s_identifiers.size()) {
		cout<<"IDENTIFIER: 				"<<s_identifiers.size()<<"			";
		printset(s_identifiers);
		cout<<endl;
	}
	if (s_type.size()) {
		cout<<"TYPE: 					"<<s_type.size()<<"			";
		printset(s_type);
		cout<<endl;
	}
	if (numOpAsgn) {
		cout<<"OP_ASGN: 				"<<numOpAsgn<<"			";
		cout<<"<-";
		cout<<endl;
	}
	if (numOpImplies) {
		cout<<"OP_IMPLIES:				"<<numOpImplies<<"			";
		cout<<"=>";
		cout<<endl;
	}
	if (s_integer.size()) {
		cout<<"INTEGER: 				"<<s_integer.size()<<"			";
		printset(s_integer);
		cout<<endl;
	}
	if (s_strings.size()) {
		cout<<"STRING:					"<<s_strings.size()<<"			";
		printset(s_strings);
		cout<<endl;
	}
	if (numColon) {
		cout<<"COLON:					"<<numColon<<"			";
		cout<<":";
		cout<<endl;
	}
	if (numStmtTerminator) {
		cout<<"STMT_TERMINATOR: 			"<<numStmtTerminator<<"			";
		cout<<";";
		cout<<endl;
	}
	if (numBlockBegin) {
		cout<<"BLOCK_BEGIN: 				"<<numBlockBegin<<"			";
		cout<<"{";
		cout<<endl;
	}
	if (numBlockEnd) {
		cout<<"BLOCK_END: 				"<<numBlockEnd<<"			";
		cout<<"}";
		cout<<endl;
	}
	if (numParanOpen) {
		cout<<"PARAN_OPEN: 				"<<numParanOpen<<"			";
		cout<<"(";
		cout<<endl;
	}
	if (numParanClose) {
		cout<<"PARAN_CLOSE: 				"<<numParanClose<<"			";
		cout<<")";
		cout<<endl;
	}
	if (numArrayOpen) {
		cout<<"ARRAY_OPEN:	 			"<<numArrayOpen<<"			";
		cout<<"[";
		cout<<endl;
	}
	if (numArrayClose) {
		cout<<"ARRAY_CLOSE: 				"<<numArrayClose<<"			";
		cout<<"]";
		cout<<endl;
	}
	if (s_op_arithmetic.size()) {
		cout<<"OP_ARITHMETIC:				"<<s_op_arithmetic.size()<<"			";
		printset(s_op_arithmetic);
		cout<<endl;
	}
	if (s_op_relational.size()) {
		cout<<"OP_RELATIONAL:				"<<s_op_relational.size()<<"			";
		printset(s_op_relational);
		cout<<endl;
	}
	cout<<"--------------------------------------------------------------------------"<<endl;
	if(s_unrecog.size()){
		cout<<"UNRECOGNIZED CHARACTERS: "<<endl;
		printset(s_unrecog);
	}
	return 0;
}

